<a href="https://colab.research.google.com/github/flaviocrispin/tecnicaprogramacao/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Ensino/DimCustomer.csv")

In [ ]:
df.tail()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
18864,18864,19141,731,Not Provided,Not Provided,1970-02-01,M,F,10000000.0,2.0,1.0,Bachelors,Management,1.0,0.0
18865,18865,19142,732,Not Provided,Not Provided,1989-02-16,S,F,10000000.0,1.0,1.0,Bachelors,Manual,1.0,0.0
18866,18866,19143,733,Not Provided,Not Provided,1980-07-23,M,M,10000000.0,3.0,1.0,Graduate Degree,Management,1.0,2.0
18867,18867,19144,734,Not Provided,Not Provided,1982-08-28,M,M,10000000.0,1.0,0.0,Partial College,Management,0.0,1.0
18868,18868,19145,735,Not Provided,Not Provided,1967-06-19,S,M,10000000.0,5.0,5.0,Partial High School,Clerical,1.0,2.0

In [ ]:
df.head()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18869 entries, 0 to 18868
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            18869 non-null  int64
 1   CustomerKey           18869 non-null  int64
 2   GeographyKey          18869 non-null  int64
 3   FirstName             18869 non-null  object
 4   LastName              18869 non-null  object
 5   BirthDate             18869 non-null  object
 6   MaritalStatus         18869 non-null  object
 7   Gender                18869 non-null  object
 8   YearlyIncome          18869 non-null  float64
 9   TotalChildren         18869 non-null  float64
 10  NumberChildrenAtHome  18869 non-null  float64
 11  Education             18869 non-null  object
 12  Occupation            18869 non-null  object
 13  HouseOwnerFlag        18869 non-null  float64
 14  NumberCarsOwned       18869 non-null  float64
dtypes: float64(5), int64(3), object(7)
memory usage: 2.2+ MB

In [ ]:
df.shape

(18869, 15)

In [ ]:
df["salario_mensal"] = df['YearlyIncome'] / 12

In [ ]:
df.head()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,salario_mensal
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0,7500.000000
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0,5000.000000
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0,5000.000000
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0,5833.333333
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,6666.666667

In [ ]:
df['nomenovacoluna'] = 1

In [ ]:
df.tail()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,salario_mensal,nomenovacoluna
18864,18864,19141,731,Not Provided,Not Provided,1970-02-01,M,F,10000000.0,2.0,1.0,Bachelors,Management,1.0,0.0,833333.333333,1
18865,18865,19142,732,Not Provided,Not Provided,1989-02-16,S,F,10000000.0,1.0,1.0,Bachelors,Manual,1.0,0.0,833333.333333,1
18866,18866,19143,733,Not Provided,Not Provided,1980-07-23,M,M,10000000.0,3.0,1.0,Graduate Degree,Management,1.0,2.0,833333.333333,1
18867,18867,19144,734,Not Provided,Not Provided,1982-08-28,M,M,10000000.0,1.0,0.0,Partial College,Management,0.0,1.0,833333.333333,1
18868,18868,19145,735,Not Provided,Not Provided,1967-06-19,S,M,10000000.0,5.0,5.0,Partial High School,Clerical,1.0,2.0,833333.333333,1

In [ ]:
df.drop("nomenovacoluna", axis=1, inplace=True)

In [ ]:
df.head()

,Unnamed: 0,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,salario_mensal
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0,7500.000000
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0,5000.000000
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0,5000.000000
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0,5833.333333
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,6666.666667

In [ ]:
df.drop ('Unnamed: 0', inplace=True, axis=1)

In [ ]:
df.head()

,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,salario_mensal
0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0,7500.000000
1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0,5000.000000
2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0,5000.000000
3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0,5833.333333
4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,6666.666667

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18869 entries, 0 to 18868
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerKey           18869 non-null  int64
 1   GeographyKey          18869 non-null  int64
 2   FirstName             18869 non-null  object
 3   LastName              18869 non-null  object
 4   BirthDate             18869 non-null  object
 5   MaritalStatus         18869 non-null  object
 6   Gender                18869 non-null  object
 7   YearlyIncome          18869 non-null  float64
 8   TotalChildren         18869 non-null  float64
 9   NumberChildrenAtHome  18869 non-null  float64
 10  Education             18869 non-null  object
 11  Occupation            18869 non-null  object
 12  HouseOwnerFlag        18869 non-null  float64
 13  NumberCarsOwned       18869 non-null  float64
 14  salario_mensal        18869 non-null  float64
dtypes: float64(6), int64(2), object(7)
memory usage: 2.2+ MB

In [ ]:
df['BirthDate'] = pd.to_datetime(df['BirthDate'])

In [ ]:
df.head()

,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,salario_mensal
0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0,7500.000000
1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0,5000.000000
2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0,5000.000000
3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0,5833.333333
4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,6666.666667

In [ ]:
df.drop('BithDate', inplace=True, axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18869 entries, 0 to 18868
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerKey           18869 non-null  int64
 1   GeographyKey          18869 non-null  int64
 2   FirstName             18869 non-null  object
 3   LastName              18869 non-null  object
 4   BirthDate             18869 non-null  datetime64[ns]
 5   MaritalStatus         18869 non-null  object
 6   Gender                18869 non-null  object
 7   YearlyIncome          18869 non-null  float64
 8   TotalChildren         18869 non-null  float64
 9   NumberChildrenAtHome  18869 non-null  float64
 10  Education             18869 non-null  object
 11  Occupation            18869 non-null  object
 12  HouseOwnerFlag        18869 non-null  float64
 13  NumberCarsOwned       18869 non-null  float64
 14  salario_mensal        18869 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(2), object(6)
memory usage: 2.2+ MB

In [ ]:
df.describe()

,CustomerKey,GeographyKey,BirthDate,YearlyIncome,TotalChildren,NumberChildrenAtHome,HouseOwnerFlag,NumberCarsOwned,salario_mensal
count,18869.000000,18869.000000,18869,1.886900e+04,18869.000000,18869.000000,18869.000000,18869.000000,18869.000000
mean,9440.631459,574.910435,1962-05-05 06:14:05.958980352,2.601749e+05,1.856219,1.034077,0.673274,1.513753,21681.240836
min,1.000000,423.000000,1910-08-13 00:00:00,1.000000e+04,0.000000,0.000000,0.000000,0.000000,833.333333
25%,4718.000000,506.000000,1954-11-14 00:00:00,3.000000e+04,0.000000,0.000000,0.000000,1.000000,2500.000000
50%,9435.000000,568.000000,1963-11-02 00:00:00,6.000000e+04,2.000000,0.000000,1.000000,2.000000,5000.000000
75%,14152.000000,645.000000,1970-12-27 00:00:00,8.000000e+04,3.000000,2.000000,1.000000,2.000000,6666.666667
max,19145.000000,952.000000,1990-12-27 00:00:00,1.000000e+07,5.000000,5.000000,1.000000,4.000000,833333.333333
std,5456.841811,84.163867,NaN,1.406071e+06,1.615868,1.541922,0.469029,1.146417,117172.578694

In [ ]:
media_salario = df['YearlyIncome'].mean()
desvio_salario = df['YearlyIncome'].std()

In [ ]:
media_salario

np.float64(260174.8900312682)

In [ ]:
print (f"A Média de salário anual é: R${(round(media_salario), 3)}")

A Média de salário anual é: R$(260175, 3)

In [ ]:
print (f"A media de salario anual é {media_salario}:", )

A media de salario anual é : 260174.8900312682

In [ ]:
print(f"A Média de salário anual é: R$ {round(media_salario)}")

A Média de salário anual é: R$ 260175

In [ ]:
df['Gender'].value_counts()

Gender
M    9525
F    9344
Name: count, dtype: int64

In [ ]:
df.head()

,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,salario_mensal
0,1,680,Jon,Yang,1966-04-08,M,M,90000.0,2.0,0.0,Bachelors,Professional,1.0,0.0,7500.000000
1,2,692,Eugene,Huang,1965-05-14,S,M,60000.0,3.0,3.0,Bachelors,Professional,0.0,1.0,5000.000000
2,3,493,Ruben,Torres,1965-08-12,M,M,60000.0,3.0,3.0,Bachelors,Professional,1.0,1.0,5000.000000
3,4,519,Christy,Zhu,1968-02-15,S,F,70000.0,0.0,0.0,Bachelors,Professional,0.0,1.0,5833.333333
4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.0,5.0,5.0,Bachelors,Professional,1.0,4.0,6666.666667